
DROP DATABASE IF EXISTS Chinook_dw;
CREATE DATABASE Chinook_dw;

USE Chinook_dw;

CREATE TABLE dim_customer (
	CUSTOMER_ID INT,
	CUSTOMERFIRSTNAME VARCHAR(255),
	CUSTOMERLASTNAME VARCHAR(255),
	CITY VARCHAR(255),
	COUNTRY VARCHAR(255),
	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE dim_track (
	TRACK_ID INT,
	TRACKNAME VARCHAR(255),
	ALBUMTITLE VARCHAR(255),
	ARSTISTNAME VARCHAR(255),
	PRIMARY KEY (TRACK_ID)
);

CREATE TABLE dim_time (
	TIME_ID DATETIME,
	YEAR_ID INT,
	MONTH_ID INT,
	MONTH_NAME VARCHAR(255),
	DAY_ID	INT,
	PRIMARY KEY (TIME_ID)
);

CREATE TABLE fact_invoice (
	INVOICE_ID INT,
	INVOICELINE_ID INT,
	CUSTOMER_ID INT,
	TRACK_ID INT,
	QUANTITYORDERED INT,
	PRICEEACH DOUBLE,
	LINETOTAL DOUBLE,
	INVOICE_DATE DATETIME,
	PRIMARY KEY (INVOICE_ID,INVOICELINE_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES dim_customer (CUSTOMER_ID),
	FOREIGN KEY (TRACK_ID) REFERENCES dim_track (TRACK_ID),
	FOREIGN KEY (INVOICE_DATE) REFERENCES dim_time (TIME_ID)
);